<<<<<<<HEAD

branch 'TestBranch'
browser=edge
url=https://www.google.com
#=======================================================================
#                           TestBranch
#=======================================================================

Environment = Test

#=======================================================================
#                           Folder and file path
#=======================================================================
