name: Feature - Safe defaults

on:
  push:
    paths:
      - "src/main/resources/**"
      - "pom.xml"
      - ".mvn/**"
  pull_request:
    paths:
      - "src/main/resources/**"
      - "pom.xml"
      - ".mvn/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/practice-feature-checks.yml
